- name: install and start mysql
  hosts: frontend
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql-serer
      state: present

  - name: start mysql
    ansible.builtin.service:
      name: mysql-servsr
      state: started
      enabled: yes