# - name: conditions
#   hosts: local
#   connection: local
#   vars:
#     number: 12
#   tasks:
#   - name: print given number is lessthan 10
#     ansible.builtin.debug:
#       msg: "Given number: {{number}} is  lessthan 10"
#     when: number < 10

- name: conditions
  hosts: local
  connection: local
  vars:
   numbers: [1 , 2,5, 7, 6, 9 ]
  tasks:
  - name: print numbers less  than 5
    ansible.builtin.debug:
      msg: " The numbers which are greater than 5: {{ numbers }}"
    when: numbers > 5
